AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    # Enable Logs
    MethodSettings:
      - ResourcePath: "/*"
        HttpMethod: "*"
        DataTraceEnabled: True
        LoggingLevel: INFO
        MetricsEnabled: True

Resources:
  # Quando 
  ## Lambda Function
  Quando:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./src/quando
      Handler: main.handler
      Runtime: python3.8

  ## Execution Role
  LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
          AssumeRolePolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Principal:
                    Service:
                      - apigateway.amazonaws.com
                  Action:
                    - 'sts:AssumeRole'
          Policies:
              - PolicyName: AllowLambdaExec
                PolicyDocument:
                  Version: "2012-10-17"
                  Statement:
                    - Effect: Allow
                      Action: 'lambda:InvokeFunction'
                      Resource: !GetAtt Quando.Arn

  # API Gateway
  ## Gateway
  ApiGW:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer:
          AuthorizationType: "NONE"
      DefinitionBody: # an OpenApi definition
          "Fn::Transform":
              Name: "AWS::Include"
              Parameters:
                  Location: "openapi.yml"
      EndpointConfiguration:
          Type: REGIONAL
    DependsOn:
      - Quando
      - ApiCWLRoleArn

  ## Cloudwatch Role Attachment
  ApiCWLRoleArn:
      Type: AWS::ApiGateway::Account
      Properties: 
        CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  ## Cloudwatch Role
  CloudWatchRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Path: /
        ManagedPolicyArns:
          - 'arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'

Outputs:
  QuandoEP:
    Description: URL of the Quando API endpoint
    Value: !Sub "https://${ApiGW}.execute-api.${AWS::Region}.amazonaws.com/prod/quando"
